Sea Dragons: ButtonState Class Reference
ButtonState Class Reference
A class used to keep track of the state of buttons on a joystick.
#include <ButtonState.h>
Classes
struct ButtonStateType
Struct that keeps track of the button state.
Public Member Functions
ButtonState (frc::GenericHID &joystick)
Construct a new ButtonState object.
bool isButton1Pressed ()
Checks if button 1 of the joystick is pressed.
bool isButton2Pressed ()
Checks if button 2 of the joystick is pressed.
bool isButton3Pressed ()
Checks if button 3 of the joystick is pressed.
bool isButton4Pressed ()
Checks if button 4 of the joystick is pressed.
bool isButton5Pressed ()
Checks if button 5 of the joystick is pressed.
bool isButton6Pressed ()
Checks if button 6 of the joystick is pressed.
bool isButton7Pressed ()
Checks if button 7 of the joystick is pressed.
bool isButton8Pressed ()
Checks if button 8 of the joystick is pressed.
bool isButton9Pressed ()
Checks if button 9 of the joystick is pressed.
bool isButton10Pressed ()
Checks if button 10 of the joystick is pressed.
bool isButton11Pressed ()
Checks if button 11 of the joystick is pressed.
bool isButton12Pressed ()
Checks if button 12 of the joystick is pressed.
Private Member Functions
void updateState ()
Updates the button states.
Private Attributes
ButtonStateType m_joystickButtonState
frc::GenericHID & m_joystick
Detailed Description
A class used to keep track of the state of buttons on a joystick.
Definition at line 10 of file ButtonState.h.
Constructor & Destructor Documentation
ButtonState()
ButtonState::ButtonState (frc::GenericHID & joystick)
Construct a new ButtonState object.
Parameters
joystick A joystick object created from frc/Joystick.h
This class is used to read the state of the joystick because we had trouble with reading the joystick's state consistently
Definition at line 10 of file ButtonState.cpp.
                                                 :
   m_joystick(joystick)
 {
 }
Member Function Documentation
isButton10Pressed()
bool ButtonState::isButton10Pressed ()
Checks if button 10 of the joystick is pressed.
Returns
true
false
Definition at line 201 of file ButtonState.cpp.
{
   updateState();
   return m_joystickButtonState.button10Pressed;
 }
isButton11Pressed()
bool ButtonState::isButton11Pressed ()
Checks if button 11 of the joystick is pressed.
Returns
true
false
Definition at line 211 of file ButtonState.cpp.
{
   updateState();
   return m_joystickButtonState.button11Pressed;
 }
isButton12Pressed()
bool ButtonState::isButton12Pressed ()
Checks if button 12 of the joystick is pressed.
Returns
true
false
Definition at line 221 of file ButtonState.cpp.
{
   updateState();
   return m_joystickButtonState.button12Pressed;
 }
isButton1Pressed()
bool ButtonState::isButton1Pressed ()
Checks if button 1 of the joystick is pressed.
Returns
true
false
Definition at line 111 of file ButtonState.cpp.
{
   updateState();
   return m_joystickButtonState.button1Pressed;
 }
isButton2Pressed()
bool ButtonState::isButton2Pressed ()
Checks if button 2 of the joystick is pressed.
Returns
true
false
Definition at line 121 of file ButtonState.cpp.
{
   updateState();
   return m_joystickButtonState.button2Pressed;
 }
isButton3Pressed()
bool ButtonState::isButton3Pressed ()
Checks if button 3 of the joystick is pressed.
Returns
true
false
Definition at line 131 of file ButtonState.cpp.
{
   updateState();
   return m_joystickButtonState.button3Pressed;
 }
isButton4Pressed()
bool ButtonState::isButton4Pressed ()
Checks if button 4 of the joystick is pressed.
Returns
true
false
Definition at line 141 of file ButtonState.cpp.
{
   updateState();
   return m_joystickButtonState.button4Pressed;
 }
isButton5Pressed()
bool ButtonState::isButton5Pressed ()
Checks if button 5 of the joystick is pressed.
Returns
true
false
Definition at line 151 of file ButtonState.cpp.
{
   updateState();
   return m_joystickButtonState.button5Pressed;
 }
isButton6Pressed()
bool ButtonState::isButton6Pressed ()
Checks if button 6 of the joystick is pressed.
Returns
true
false
Definition at line 161 of file ButtonState.cpp.
{
   updateState();
   return m_joystickButtonState.button6Pressed;
 }
isButton7Pressed()
bool ButtonState::isButton7Pressed ()
Checks if button 7 of the joystick is pressed.
Returns
true
false
Definition at line 171 of file ButtonState.cpp.
{
   updateState();
   return m_joystickButtonState.button7Pressed;
 }
isButton8Pressed()
bool ButtonState::isButton8Pressed ()
Checks if button 8 of the joystick is pressed.
Returns
true
false
Definition at line 181 of file ButtonState.cpp.
{
   updateState();
   return m_joystickButtonState.button8Pressed;
 }
isButton9Pressed()
bool ButtonState::isButton9Pressed ()
Checks if button 9 of the joystick is pressed.
Returns
true
false
Definition at line 191 of file ButtonState.cpp.
{
   updateState();
   return m_joystickButtonState.button9Pressed;
 }
updateState()
void ButtonState::updateState () private
Updates the button states.
Definition at line 19 of file ButtonState.cpp.
{
   if (m_joystick.GetRawButtonPressed(1)) {
     m_joystickButtonState.button1Pressed = true;
   }
   else if (m_joystick.GetRawButtonReleased(1)) {
     m_joystickButtonState.button1Pressed = false;
   }
   if (m_joystick.GetRawButtonPressed(2)) {
     m_joystickButtonState.button2Pressed = true;
   }
   else if (m_joystick.GetRawButtonReleased(2)) {
     m_joystickButtonState.button2Pressed = false;
   }
   if (m_joystick.GetRawButtonPressed(3)) {
     m_joystickButtonState.button3Pressed = true;
   }
   else if (m_joystick.GetRawButtonReleased(3)) {
     m_joystickButtonState.button3Pressed = false;
   }
   if (m_joystick.GetRawButtonPressed(4)) {
     m_joystickButtonState.button4Pressed = true;
   }
   else if (m_joystick.GetRawButtonReleased(4)) {
     m_joystickButtonState.button4Pressed = false;
   }
   if (m_joystick.GetRawButtonPressed(5)) {
     m_joystickButtonState.button5Pressed = true;
   }
   else if (m_joystick.GetRawButtonReleased(5)) {
     m_joystickButtonState.button5Pressed = false;
   }
   if (m_joystick.GetRawButtonPressed(6)) {
     m_joystickButtonState.button6Pressed = true;
   }
   else if (m_joystick.GetRawButtonReleased(6)) {
     m_joystickButtonState.button6Pressed = false;
   }
   if (m_joystick.GetRawButtonPressed(7)) {
     m_joystickButtonState.button7Pressed = true;
   }
   else if (m_joystick.GetRawButtonReleased(7)) {
     m_joystickButtonState.button7Pressed = false;
   }
   if (m_joystick.GetRawButtonPressed(8)) {
     m_joystickButtonState.button8Pressed = true;
   }
   else if (m_joystick.GetRawButtonReleased(8)) {
     m_joystickButtonState.button8Pressed = false;
   }
   if (m_joystick.GetRawButtonPressed(9)) {
     m_joystickButtonState.button9Pressed = true;
   }
   else if (m_joystick.GetRawButtonReleased(9)) {
     m_joystickButtonState.button9Pressed = false;
   }
   if (m_joystick.GetRawButtonPressed(10)) {
     m_joystickButtonState.button10Pressed = true;
   }
   else if (m_joystick.GetRawButtonReleased(10)) {
     m_joystickButtonState.button10Pressed = false;
   }
   if (m_joystick.GetRawButtonPressed(11)) {
     m_joystickButtonState.button11Pressed = true;
   }
   else if (m_joystick.GetRawButtonReleased(11)) {
     m_joystickButtonState.button11Pressed = false;
   }
   if (m_joystick.GetRawButtonPressed(12)) {
     m_joystickButtonState.button12Pressed = true;
   }
   else if (m_joystick.GetRawButtonReleased(12)) {
     m_joystickButtonState.button12Pressed = false;
   }
 }
Referenced by isButton10Pressed(), isButton11Pressed(), isButton12Pressed(), isButton1Pressed(), isButton2Pressed(), isButton3Pressed(), isButton4Pressed(), isButton5Pressed(), isButton6Pressed(), isButton7Pressed(), isButton8Pressed(), and isButton9Pressed().
Member Data Documentation
m_joystick
frc::GenericHID& ButtonState::m_joystick private
Definition at line 127 of file ButtonState.h.
Referenced by updateState().
m_joystickButtonState
ButtonStateType ButtonState::m_joystickButtonState private
Definition at line 126 of file ButtonState.h.
Referenced by isButton10Pressed(), isButton11Pressed(), isButton12Pressed(), isButton1Pressed(), isButton2Pressed(), isButton3Pressed(), isButton4Pressed(), isButton5Pressed(), isButton6Pressed(), isButton7Pressed(), isButton8Pressed(), isButton9Pressed(), and updateState().
The documentation for this class was generated from the following files:
src/main/include/ButtonState.h
src/main/cpp/ButtonState.cpp