Sea Dragons: SafeData< T > Class Template Reference
SafeData< T > Class Template Reference
This data will be thread safe using this class.
#include <SafeData.hpp>
Public Member Functions
void set (T data)
Sets the data to be read by another thread.
T get ()
Returns the data.
void processLocked (std::function< void(T &)> func)
A function used to get and modify T
void processLocked (std::function< void(const T &)> func) const
A function used to get and modify T
Private Attributes
std::mutex m_mutex
T m_data
Detailed Description
template<typename T>
class SafeData< T >
This data will be thread safe using this class.
This can be used if you want to get data from one thread to another
Template Parameters
T
Definition at line 12 of file SafeData.hpp.
Member Function Documentation
get()
template<typename T > T SafeData< T >::get () inline
Returns the data.
Returns
T The data type
Definition at line 28 of file SafeData.hpp.
                 {
             std::lock_guard<std::mutex> lock(m_mutex);
             return m_data;
         }
Referenced by VisionController::putOutline(), Autonomous::start(), AutonomousDrive::update(), and Autonomous::update().
processLocked() [1/2]
template<typename T > void SafeData< T >::processLocked (std::function< void(const T &)> func) const inline
A function used to get and modify T
Parameters
func A function that takes in a T reference
The funtion then gets called with the T type
In the function you would program what you wanted to do the T
This is usefull if you need to get T in order to modify it or for any other reason
Definition at line 52 of file SafeData.hpp.
{
             std::lock_guard<std::mutex> lock(m_mutex);
             func(m_data);
         }
processLocked() [2/2]
template<typename T > void SafeData< T >::processLocked (std::function< void(T &)> func) inline
A function used to get and modify T
Parameters
func A function that takes in a T reference
The funtion then gets called with the T type
In the function you would program what you wanted to do the T
This is usefull if you need to get T in order to modify it or for any other reason
Definition at line 40 of file SafeData.hpp.
{
             std::lock_guard<std::mutex> lock(m_mutex);
             func(m_data);
         }
Referenced by VisionSense::operator()(), VisionController::putOutline(), VisionController::start(), VisionController::updateFrame(), and VisionController::VisionController().
set()
template<typename T > void SafeData< T >::set (T data) inline
Sets the data to be read by another thread.
Parameters
data The data
Definition at line 19 of file SafeData.hpp.
{
             std::lock_guard<std::mutex> lock(m_mutex);
             m_data = data;
         }
Referenced by Autonomous::Autonomous(), and VisionSense::operator()().
Member Data Documentation
m_data
template<typename T > T SafeData< T >::m_data private
Definition at line 58 of file SafeData.hpp.
Referenced by SafeData< cv::Mat >::get(), SafeData< cv::Mat >::processLocked(), and SafeData< cv::Mat >::set().
m_mutex
template<typename T > std::mutex SafeData< T >::m_mutex mutable private
Definition at line 57 of file SafeData.hpp.
Referenced by SafeData< cv::Mat >::get(), SafeData< cv::Mat >::processLocked(), and SafeData< cv::Mat >::set().
The documentation for this class was generated from the following file:
src/main/include/SafeData.hpp